[options]
db_host = db
db_port = 5432
db_name = odoo
db_user = odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
http_port = 8069
workers = 0
log_level = info
limit_time_cpu = 3600
limit_time_real = 7200
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
list_db = True
